# Generated by Django 4.2.28 on 2026-06-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_newsletter_popup', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، پاپ\u200cآپ خبرنامه در سایت نمایش داده نمی\u200cشود.', verbose_name='نمایش پاپ\u200cآپ خبرنامه')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
