"""
Django settings for Ario_Shop project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================

# Read DEBUG from environment variable, default to False for safety
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# SECRET_KEY: Read from environment. Fail loudly if missing in production.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-key-for-local-development-only-change-in-prod'
    else:
        raise ValueError(
            'DJANGO_SECRET_KEY environment variable is required in production. '
            'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
        )

# Allowed hosts configuration
# Read from environment or use defaults for development
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,::1,arya0325.pythonanywhere.com,aryaabdi1850325.pythonanywhere.com').split(',')
    if h.strip()
]
# Always ensure PythonAnywhere domains are included
for _pa_host in ['arya0325.pythonanywhere.com', 'aryaabdi1850325.pythonanywhere.com']:
    if _pa_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_pa_host)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    # Local apps
    'Core_Module',
    'Home_Module',
    'Menu_Module',
    'Contact_Module',
    'AboutUs_Module',
    'Products_Module',
    'Accounts_Module',
    'Cart_Module',
]

MIDDLEWARE = [
    # Security middleware - order matters!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ario_Shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Menu_Module.context_processors.menu_items',
                'Cart_Module.context_processors.cart_context',
                'Products_Module.context_processors.navbar_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ario_Shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Cache configuration - use Redis in production, LocMem for development
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# For production, use Redis cache:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django.core.cache.backends.redis.RedisCacheClient',
#         },
#         'KEY_PREFIX': 'ario_shop',
#         'TIMEOUT': 300,  # 5 minutes default
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "Core_Module/admin",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# احراز هویت و ماژول کاربران
AUTHENTICATION_BACKENDS = [
    'Accounts_Module.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# برای بازیابی رمز عبور (در حالت توسعه ایمیل در کنسول چاپ می‌شود)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 465
    EMAIL_HOST_USER = 'bardiaabdi1393@gmail.com'
    EMAIL_HOST_PASSWORD = 'wokw kyci lswj uqqd'
    EMAIL_USE_SSL = True
    EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'آریو شاپ <bardiaabdi1393@gmail.com>'

# =============================================================================
# N8N AUTHENTICATION WEBHOOK
# =============================================================================

N8N_WEBHOOK_URL = 'https://quiet-field-a090.mimoomim456.workers.dev/webhook/django-auth-event'
N8N_WEBHOOK_SECRET = 'ario-shop-secret-token'
OTP_EXPIRY_MINUTES = 15

# =============================================================================
# N8N ORDER CONFIRMATION WEBHOOK
# =============================================================================

N8N_ORDER_WEBHOOK_URL = 'https://quiet-field-a090.mimoomim456.workers.dev/webhook/order-paid'
N8N_ORDER_WEBHOOK_SECRET = N8N_WEBHOOK_SECRET
N8N_SENDER_EMAIL = 'bardiaabdi1393@gmail.com'

# =============================================================================
# SECURITY SETTINGS - PRODUCTION READY
# =============================================================================

# HTTPS/SSL Settings - Only enable in production!
SECURE_SSL_REDIRECT = not DEBUG  # Redirect HTTP to HTTPS only in production
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # HSTS only in production (1 year)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_REDIRECT_EXEMPT = []

# Cookie Security - Always secure, regardless of DEBUG
SESSION_COOKIE_SECURE = not DEBUG  # Secure cookies only in production (HTTPS)
SESSION_COOKIE_HTTPONLY = True  # Always safe - prevents XSS from reading cookies
SESSION_COOKIE_SAMESITE = 'Lax'  # Balance between security and usability
CSRF_COOKIE_SECURE = not DEBUG  # Secure CSRF cookies only in production (HTTPS)
CSRF_COOKIE_HTTPONLY = True  # Prevents CSRF token theft via JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'

# CSRF Settings - Allow localhost for development and production domains
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'http://[::1]',
    'http://[::1]:8000',
    'https://arya0325.pythonanywhere.com',  # PythonAnywhere production
    'https://aryaabdi1850325.pythonanywhere.com',  # PythonAnywhere production (2nd domain)
]

# Add production CSRF origins if not in debug mode
if not DEBUG:
    # Add your production domains here
    # CSRF_TRUSTED_ORIGINS.extend(['https://your-domain.com'])
    pass

# X-Frame-Options - Clickjacking protection
X_FRAME_OPTIONS = 'DENY'

# X-Content-Type-Options - MIME sniffing protection
SECURE_CONTENT_TYPE_NOSNIFF = True  # Always enabled

# X-XSS-Protection (legacy but still recommended)
SECURE_BROWSER_XSS_FILTER = True  # Always enabled

# SSL/TLS Settings - Only in production
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# Referrer Policy - Control referrer information sent with requests
REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Permissions Policy - Control browser features
PERMISSIONS_POLICY = {
    'geolocation': (),
    'microphone': (),
    'camera': (),
    'payment': (),
}

# Content Security Policy - Prevent XSS and injection attacks
# Strict CSP for production, relaxed for development
if not DEBUG:
    # Production CSP - customize based on your static assets
    SECURE_CONTENT_SECURITY_POLICY = """
        default-src 'self';
        script-src 'self' 'unsafe-inline' 'unsafe-eval';
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com;
        img-src 'self' data: https:;
        connect-src 'self';
        worker-src 'self';
        frame-ancestors 'none';
    """.replace('\n', ' ').strip()
else:
    # Development CSP - more permissive but still logs violations
    SECURE_CONTENT_SECURITY_POLICY = """
        default-src 'self' 'unsafe-inline' 'unsafe-eval';
        script-src 'self' 'unsafe-inline' 'unsafe-eval';
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com data:;
        img-src 'self' data: https: blob:;
        connect-src 'self';
        frame-ancestors 'none';
    """.replace('\n', ' ').strip()

# Log CSP violations in development
SECURE_CSP_LOG_VIOLATIONS = DEBUG

# =============================================================================
# ADMIN CUSTOMIZATION
# =============================================================================

# Admin site header and title
ADMIN_SITE_HEADER = 'پنل مدیریت آریو شاپ'
ADMIN_SITE_TITLE = 'پنل مدیریت آریو شاپ'
ADMIN_INDEX_TITLE = 'به پنل مدیریت خوش آمدید'

# Hide admin in development (optional - uncomment in production)
# ADMIN_URL = 'admin-panel/'  # Change 'admin/' to something else

# =============================================================================
# PASSWORD HASHING - PRODUCTION SECURITY
# =============================================================================

# Use Argon2 in production (more secure than PBKDF2)
# PBKDF2 is used as fallback for compatibility
if not DEBUG:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.Argon2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    ]
else:
    # Use PBKDF2 for development (faster)
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    ]

# =============================================================================
# RATE LIMITING SETTINGS
# =============================================================================

# Rate limiting configuration using django-ratelimit
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_CACHE_PREFIX = 'rl'

# Rate limit defaults (can be overridden per-view)
RATELIMIT_DEFAULT = '10/m'  # 10 requests per minute by default

# Login rate limiting - prevent brute force attacks
LOGIN_RATE_LIMIT = '5/m'  # 5 login attempts per minute
LOGIN_RATE_LIMIT_USER = '10/m'  # Per user limit

# =============================================================================
# SESSION SETTINGS
# =============================================================================

# Session configuration
SESSION_COOKIE_AGE = 60 * 60 * 24 * 2  # 2 days in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# =============================================================================
# FILE UPLOAD SECURITY
# =============================================================================

# Maximum upload size (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# File upload permissions
FILE_UPLOAD_PERMISSIONS = 0o644

# =============================================================================
# CACHE KEY PREFIX (to avoid conflicts)
# =============================================================================

CACHE_KEY_PREFIX = 'ario_shop_'

# =============================================================================
# DEFAULT AUTO FIELD
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'