"""
Django settings for Ario_Shop project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================

# Detect if running in production by checking if DEBUG is explicitly set
# Default to True for local development, False for production
DEBUG = True  # تغییر به False برای محیط production

# Generate a secure secret key based on environment detection
# In production, use a fixed key. For development, use a default.
def get_secret_key():
    """
    Generate or retrieve a secure secret key.
    For production, this should be a strong, random key.
    For development, we use a fixed key for convenience.
    """
    # In production (DEBUG=False), use a strong static key
    # Change this in production to a truly random key!
    if not DEBUG:
        return 'prod-secret-key-change-this-in-production-use-openssl-rand-hex-32'
    # For development, use a fixed key
    return 'django-insecure-dev-key-for-local-development-only-change-in-prod'

SECRET_KEY = get_secret_key()

# Allowed hosts configuration
# For production, add your actual domain names
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '::1',
    'arya0325.pythonanywhere.com',  # PythonAnywhere production domain
]

# Add production domains if not in debug mode
if not DEBUG:
    # Add your production domains here
    # ALLOWED_HOSTS.extend(['your-domain.com', 'www.your-domain.com'])
    pass

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Home_Module',
    'Menu_Module',
    'Contact_Module',
    'AboutUs_Module',
    'Products_Module',
    'Accounts_Module',
    'Cart_Module',
]

MIDDLEWARE = [
    # Security middleware - order matters!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ario_Shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Menu_Module.context_processors.menu_items',
                'Cart_Module.context_processors.cart_context',
                'Products_Module.context_processors.navbar_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ario_Shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Cache configuration - use Redis in production, LocMem for development
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# For production, use Redis cache:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django.core.cache.backends.redis.RedisCacheClient',
#         },
#         'KEY_PREFIX': 'ario_shop',
#         'TIMEOUT': 300,  # 5 minutes default
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# احراز هویت و ماژول کاربران
AUTHENTICATION_BACKENDS = [
    'Accounts_Module.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# برای بازیابی رمز عبور (در حالت توسعه ایمیل در کنسول چاپ می‌شود)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@arioshop.local'

# =============================================================================
# SECURITY SETTINGS - PRODUCTION READY
# =============================================================================

# HTTPS/SSL Settings - Only enable in production!
SECURE_SSL_REDIRECT = not DEBUG  # Redirect HTTP to HTTPS only in production
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # HSTS only in production (1 year)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_REDIRECT_EXEMPT = []

# Cookie Security - Always secure, regardless of DEBUG
SESSION_COOKIE_SECURE = True  # Always use secure cookies
SESSION_COOKIE_HTTPONLY = True  # Always safe - prevents XSS from reading cookies
SESSION_COOKIE_SAMESITE = 'Lax'  # Balance between security and usability
CSRF_COOKIE_SECURE = True  # Always use secure CSRF cookies
CSRF_COOKIE_HTTPONLY = True  # Prevents CSRF token theft via JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'

# CSRF Settings - Allow localhost for development and production domains
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'http://[::1]',
    'http://[::1]:8000',
    'https://arya0325.pythonanywhere.com',  # PythonAnywhere production
]

# Add production CSRF origins if not in debug mode
if not DEBUG:
    # Add your production domains here
    # CSRF_TRUSTED_ORIGINS.extend(['https://your-domain.com'])
    pass

# X-Frame-Options - Clickjacking protection
X_FRAME_OPTIONS = 'DENY'

# X-Content-Type-Options - MIME sniffing protection
SECURE_CONTENT_TYPE_NOSNIFF = True  # Always enabled

# X-XSS-Protection (legacy but still recommended)
SECURE_BROWSER_XSS_FILTER = True  # Always enabled

# SSL/TLS Settings - Only in production
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# Referrer Policy - Control referrer information sent with requests
REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Permissions Policy - Control browser features
PERMISSIONS_POLICY = {
    'geolocation': (),
    'microphone': (),
    'camera': (),
    'payment': (),
}

# Content Security Policy - Prevent XSS and injection attacks
# Strict CSP for production, relaxed for development
if not DEBUG:
    # Production CSP - customize based on your static assets
    SECURE_CONTENT_SECURITY_POLICY = """
        default-src 'self';
        script-src 'self' 'unsafe-inline' 'unsafe-eval';
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com;
        img-src 'self' data: https:;
        connect-src 'self';
        frame-ancestors 'none';
    """.replace('\n', ' ').strip()
else:
    # Development CSP - more permissive but still logs violations
    SECURE_CONTENT_SECURITY_POLICY = """
        default-src 'self' 'unsafe-inline' 'unsafe-eval';
        script-src 'self' 'unsafe-inline' 'unsafe-eval';
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com data:;
        img-src 'self' data: https: blob:;
        connect-src 'self';
        frame-ancestors 'none';
    """.replace('\n', ' ').strip()

# Log CSP violations in development
SECURE_CSP_LOG_VIOLATIONS = DEBUG

# =============================================================================
# ADMIN CUSTOMIZATION
# =============================================================================

# Admin site header and title
ADMIN_SITE_HEADER = 'پنل مدیریت آریو شاپ'
ADMIN_SITE_TITLE = 'پنل مدیریت آریو شاپ'
ADMIN_INDEX_TITLE = 'به پنل مدیریت خوش آمدید'

# Hide admin in development (optional - uncomment in production)
# ADMIN_URL = 'admin-panel/'  # Change 'admin/' to something else

# =============================================================================
# PASSWORD HASHING - PRODUCTION SECURITY
# =============================================================================

# Use Argon2 in production (more secure than PBKDF2)
# PBKDF2 is used as fallback for compatibility
if not DEBUG:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.Argon2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    ]
else:
    # Use PBKDF2 for development (faster)
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    ]

# =============================================================================
# RATE LIMITING SETTINGS
# =============================================================================

# Rate limiting configuration using django-ratelimit
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_CACHE_PREFIX = 'rl'

# Rate limit defaults (can be overridden per-view)
RATELIMIT_DEFAULT = '10/m'  # 10 requests per minute by default

# Login rate limiting - prevent brute force attacks
LOGIN_RATE_LIMIT = '5/m'  # 5 login attempts per minute
LOGIN_RATE_LIMIT_USER = '10/m'  # Per user limit

# =============================================================================
# SESSION SETTINGS
# =============================================================================

# Session configuration
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Regenerate session key on login for session fixation protection
SESSION_KEY_REGENERATE = True

# =============================================================================
# FILE UPLOAD SECURITY
# =============================================================================

# Maximum upload size (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# File upload permissions
FILE_UPLOAD_PERMISSIONS = 0o644

# =============================================================================
# CACHE KEY PREFIX (to avoid conflicts)
# =============================================================================

CACHE_KEY_PREFIX = 'ario_shop_'