# Generated by Django 6.0 on 2026-02-15 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Module', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Discount code')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], default='percent', max_length=20, verbose_name='Discount type')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max discount amount')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum order amount')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends at')),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total usage limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='Per-user usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Discount code',
                'verbose_name_plural': 'Discount codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Discount amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Cart_Module.discountcode', verbose_name='Discount code'),
        ),
    ]
