# Generated by Django 4.2.28 on 2026-06-13 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Module', '0004_discountcode_scope_discountcode_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', help_text='«درصدی»: مثلاً ۱۰٪ از مبلغ. «مبلغ ثابت»: مثلاً ۵۰,۰۰۰ تومان کسر می\u200cشود.', max_length=20, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='تا چه تاریخ و ساعتی این کد معتبر است. خالی بگذارید اگر بدون تاریخ انقضا باشد.', null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط برای تخفیف درصدی: حداکثر مبلغی که تخفیف می\u200cتواند داشته باشد. مثلاً اگر ۱۰٪ تخفیف با سقف ۵۰,۰۰۰ تومان، حتی اگر ۱۰٪ بیشتر شود، بیشتر از ۵۰,۰۰۰ تومان کسر نمی\u200cشود.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='سقف مبلغ تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='کاربر باید حداقل این مبلغ در سبد خرید داشته باشد تا بتواند از این کد استفاده کند. صفر یعنی بدون محدودیت.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل مبلغ سفارش (تومان)'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='از چه تاریخ و ساعتی این کد فعال می\u200cشود. خالی بگذارید اگر از همین لحظه فعال باشد.', null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='title',
            field=models.CharField(help_text='یک عنوان توصیفی برای این کد تخفیف وارد کنید. مثال: تخفیف ویژه نوروز', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='هر کاربر حداکثر چند بار می\u200cتواند از این کد استفاده کند. خالی بگذارید برای بدون محدودیت.', null=True, verbose_name='سقف استفاده هر کاربر'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='usage_limit_total',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر چند بار این کد می\u200cتواند توسط همه کاربران استفاده شود. خالی بگذارید برای بدون محدودیت.', null=True, verbose_name='سقف کل استفاده'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='این فیلد به\u200cصورت خودکار توسط سیستم به\u200cروزرسانی می\u200cشود.', verbose_name='تعداد دفعات استفاده'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.DecimalField(decimal_places=0, help_text='اگر نوع تخفیف «درصدی» است، عدد درصد را وارد کنید (مثلاً ۱۰ برای ۱۰٪). اگر «مبلغ ثابت» است، مبلغ به تومان وارد کنید.', max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Cart_Module.discountcode', verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='جمع قبل از تخفیف'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'created_at'], name='cart_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='discount_active_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code'], name='discount_code_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_number_idx'),
        ),
    ]
