# Generated by Django 6.0 on 2026-02-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.TextField(verbose_name='آدرس دفتر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone1', models.CharField(max_length=15, verbose_name='تلفن اول')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن دوم')),
                ('map_embed', models.TextField(verbose_name='کد iframe نقشه گوگل')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='لینک توییتر')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب')),
                ('pinterest_url', models.URLField(blank=True, null=True, verbose_name='لینک پینترست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام های تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
