# Generated by Django 4.2.28 on 2026-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', '-created_at'], name='contact_read_date_idx'),
        ),
    ]
