# Generated by Django 4.2.28 on 2026-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['city'], name='profile_city_idx'),
        ),
    ]
