# Generated by Django 4.2.28 on 2026-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['menu_type', 'is_active', 'parent'], name='menu_type_active_par_idx'),
        ),
    ]
