# Generated by Django 6.0 on 2026-02-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(default='دید ما', max_length=100, verbose_name='عنوان بخش دید ما')),
                ('vision_description', models.TextField(blank=True, verbose_name='متن بخش دید ما')),
                ('mission_title', models.CharField(default='ماموریت ما', max_length=100, verbose_name='عنوان بخش ماموریت ما')),
                ('mission_description', models.TextField(blank=True, verbose_name='متن بخش ماموریت ما')),
                ('who_we_are_title', models.CharField(default='ما چه کسانی هستیم', max_length=100, verbose_name='عنوان بخش ما چه کسانی هستیم')),
                ('who_we_are_subtitle', models.TextField(blank=True, verbose_name='زیر عنوان (متن رنگی)')),
                ('who_we_are_description', models.TextField(blank=True, verbose_name='متن بخش ما چه کسانی هستیم')),
                ('who_we_are_image_front', models.ImageField(blank=True, null=True, upload_to='aboutus/who_we_are/', verbose_name='تصویر جلو')),
                ('who_we_are_image_back', models.ImageField(blank=True, null=True, upload_to='aboutus/who_we_are/', verbose_name='تصویر پشت')),
                ('brands_title', models.CharField(default='برند های معروفی که با ما در حال همکاری هستند.', max_length=100, verbose_name='عنوان بخش برندها')),
                ('brands_description', models.TextField(blank=True, verbose_name='متن بخش برندها')),
                ('team_title', models.CharField(default='آشنایی با تیم ما', max_length=100, verbose_name='عنوان بخش تیم')),
                ('testimonials_title', models.CharField(default='نظرات مشتری های فروشگاه', max_length=100, verbose_name='عنوان بخش نظرات')),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'صفحه درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('logo', models.ImageField(upload_to='aboutus/brands/', verbose_name='لوگو برند')),
                ('website', models.URLField(blank=True, verbose_name='آدرس سایت برند')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('photo', models.ImageField(upload_to='aboutus/team/', verbose_name='عکس عضو')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('facebook_url', models.URLField(blank=True, verbose_name='آدرس فیسبوک')),
                ('twitter_url', models.URLField(blank=True, verbose_name='آدرس توییتر')),
                ('instagram_url', models.URLField(blank=True, verbose_name='آدرس اینستاگرام')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('customer_role', models.CharField(default='مشتری', max_length=100, verbose_name='نقش مشتری')),
                ('photo', models.ImageField(upload_to='aboutus/testimonials/', verbose_name='عکس مشتری')),
                ('review', models.TextField(verbose_name='متن نظر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['order'],
            },
        ),
    ]
