# Generated by Django 6.0 on 2026-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='aboutus/brands/', verbose_name='لوگو برند'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='aboutus/team/', verbose_name='عکس عضو'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='aboutus/testimonials/', verbose_name='عکس مشتری'),
        ),
    ]
